name: coverage
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      NATS_CLIENT_LOG: 1
      NATS_TEST_LOG: 1
    steps:
      - uses: actions/checkout@v2
      - run: docker compose up -d
        working-directory: docker
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: xdebug
          tools: phpunit, composer:v2
      - run: composer install
      - run: vendor/bin/phpunit --testsuite Tests
      - run: cat ./coverage/report.txt
