name: tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NATS_CLIENT_LOG: 1
      NATS_TEST_LOG: 1
    strategy:
      matrix:
        php: ["8.0", "8.1"]
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
      - run: docker run -d -p 4222:4222 nats --js
      - run: vendor/bin/phpunit --testsuite Tests
