name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NATS_CLIENT_LOG: 1
      NATS_TEST_LOG: 1
    strategy:
      matrix:
        php: ["8.1", "8.2"]
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: php-actions/composer@v6
      - run: docker run -d -p 4222:4222 nats --js
      - run: vendor/bin/phpunit --testsuite Tests
